// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaipeiCrimeMap.Infrastructure.Persistence;

#nullable disable

namespace TaipeiCrimeMap.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530063756_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaipeiCrimeMap.Domain.Aggregates.TheftCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("case_number");

                    b.Property<int?>("CaseType")
                        .HasColumnType("integer")
                        .HasColumnName("case_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("RawLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("raw_location");

                    b.HasKey("Id");

                    b.HasIndex("CaseNumber")
                        .IsUnique();

                    b.ToTable("theft_cases", (string)null);
                });

            modelBuilder.Entity("TaipeiCrimeMap.Domain.Aggregates.TheftCase", b =>
                {
                    b.OwnsOne("TaipeiCrimeMap.Domain.ValueObjects.District", "District", b1 =>
                        {
                            b1.Property<Guid>("TheftCaseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("district");

                            b1.HasKey("TheftCaseId");

                            b1.ToTable("theft_cases");

                            b1.WithOwner()
                                .HasForeignKey("TheftCaseId");
                        });

                    b.OwnsOne("TaipeiCrimeMap.Domain.ValueObjects.GeoCoordinate", "Coordinate", b1 =>
                        {
                            b1.Property<Guid>("TheftCaseId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("TheftCaseId");

                            b1.ToTable("theft_cases");

                            b1.WithOwner()
                                .HasForeignKey("TheftCaseId");
                        });

                    b.OwnsOne("TaipeiCrimeMap.Domain.ValueObjects.TaiwanDate", "OccurredDate", b1 =>
                        {
                            b1.Property<Guid>("TheftCaseId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("OccurredOn")
                                .HasColumnType("date")
                                .HasColumnName("occurred_date");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("occurred_date_raw");

                            b1.Property<int?>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("occurred_year");

                            b1.HasKey("TheftCaseId");

                            b1.ToTable("theft_cases");

                            b1.WithOwner()
                                .HasForeignKey("TheftCaseId");
                        });

                    b.OwnsOne("TaipeiCrimeMap.Domain.ValueObjects.TimeSlot", "TimeSlot", b1 =>
                        {
                            b1.Property<Guid>("TheftCaseId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("EndHour")
                                .HasColumnType("integer")
                                .HasColumnName("time_slot_end");

                            b1.Property<string>("RawValue")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("time_slot_raw");

                            b1.Property<int?>("StartHour")
                                .HasColumnType("integer")
                                .HasColumnName("time_slot_start");

                            b1.HasKey("TheftCaseId");

                            b1.ToTable("theft_cases");

                            b1.WithOwner()
                                .HasForeignKey("TheftCaseId");
                        });

                    b.Navigation("Coordinate");

                    b.Navigation("District");

                    b.Navigation("OccurredDate")
                        .IsRequired();

                    b.Navigation("TimeSlot");
                });
#pragma warning restore 612, 618
        }
    }
}
